services:
  - name: medmanager-server
    type: web
    env: node
    region: singapore
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: BAIDU_OCR_CLIENT_ID
        sync: false
      - key: BAIDU_OCR_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
